import { UserType } from "../user/user.type";
import { Tarif } from "../user/user.type";
import { Specialite } from "../specialite/specialite.type";
import { CiviliteType } from "../user/user.type";


export interface IMedecin {
    id: number;
	slug: string;
	password: string;
	nom: string;
	prenom: string;
	email: string;
	telephone: string;
	civilite: CiviliteType;
	adresse: string;
	longitude: string;
	latitude: string;
	user_type: UserType;
	avatar: string | any;
	adresse_2: string;
	longitude_2: string;
	latitude_2: string;
	quartier: string;
	ville: string;
	telephone_bureau: string;
	numero_ordre_medecin: string;
	competences: string[];
	autres: string;
	signature: File | null;
	responsabilite_civile: string;
	bio: string;
	date_de_naissance: Date | string;
	termes: boolean;
	condition: boolean;
	profil: string;
	specialite: Specialite | any ; 
	tarif: Tarif[];
	owner_cabinet: boolean;
	email_visibility: boolean;
	civilite_visibility: boolean;
	date_de_naissance_visibility: boolean;
	telephone_visibility: boolean;
	telephone_bureau_visibility: boolean;
	is_active: boolean;
	freelance: boolean;
	identifiant: string;
}


export type MedecinFormData = {
    slug: string;
	password: string;
	nom: string;
	prenom: string;
	email: string;
	telephone: string;
	civilite: CiviliteType;
	adresse: string;
	longitude: string;
	latitude: string;
	user_type: UserType;
	avatar: string | any;
	adresse_2: string;
	longitude_2: string;
	latitude_2: string;
	quartier: string;
	ville: string;
	telephone_bureau: string;
	numero_ordre_medecin: string;
	competences: string[];
	autres: string;
	signature: File | null;
	responsabilite_civile: string;
	bio: string;
	date_de_naissance: Date | string;
	termes: boolean;
	condition: boolean;
	profil: string;
	specialite: Specialite | any ; 
	tarif: Tarif[];
	owner_cabinet: boolean;
	email_visibility: boolean;
	civilite_visibility: boolean;
	date_de_naissance_visibility: boolean;
	telephone_visibility: boolean;
	telephone_bureau_visibility: boolean;
	is_active: boolean;
	freelance: boolean;
	identifiant: string;
}